### ISSUE TITLE
probe triggered prior to movement

### ISSUE THREAD

**Issue by seene** [zruncho3d/nudge#1]
Hey,

unfortunately I have a problem determining the nozzle position

Z works normally, but as soon as the nozzle triggers on X axis, I get the following error message: “probe triggered prior to movement” 

I am using an Idex printer with Hybrid CoreXY w/ Dual Carriage.  I have already installed “Frans-Willem's Klipper PR”.
I have also tried the troubleshooting of “viesturz/NozzleAlign” without success.

do you have any idea what could be causing this?

**Comment by seacred** [comment]
i got the same issue unfortunately.

**Comment by TTom1088** [comment]
i got the same issue. I've tried many different options. I suspect there is a problem in the software, as everything is fine in terms of hardware.

**Comment by VIN-y** [comment]
Alright. Since it seems like this issue is being discuss more over here. I will move this comment over.

Nothing really came to my mind of what could have cause you issue. So, let's try breaking this down further.

There are 4 components to the calibration probe: hardware assembly, electrical wiring, the .cfg file, and the underlying python code.

You said Z works normally. So I am assuming that, after initiated, the machine would pick up T0 and move to calibration probe pin position. Then it moved down until it triggered the probe. Then it starts the x measurement, which is where the error occur? --- If so. We can push the hardware-assembly and electrical-wiring to the back of the potential-problem queue for now. The next thing to go over is your calibrate-offsets.cfg file. That is not to say that the config is the problem, as it is just a list of numbers for your tool-head to move along.

Follow the logic above, maybe you the tip of your hotend touched the pin when it moving toward the starting position for the x calibration, which then trigger the error for safety.

So... what hotend are you using? can we see your config file? and, can you check on for the potential cause above?

**Comment by TTom1088** [comment]
I have now analyzed the problem further. I use an IDEX hybrid core xy. Z works perfectly. But as soon as X is connected, the error message "probe triggered prior to movement" appears. But only when the nozzle "triggers" the probe; manual triggering during X reversing also generates this error.

Since Z always works, I suspect there is a software error in the program. The problem is probably because the nudge switches an NC contact. The switch from viesturz uses NO logic and the problem probably does not occur there.

**Comment by TTom1088** [comment]
I have now found a solution for this online. It is a software error that only affects IDEX printers, here is the solution:

https://github.com/viesturz/klipper-toolchanger/pull/23/commits/3f7e2c1dc7e5ceac8e3972c9b5906ef8c089aa3e

**Comment by seene** [comment]
yes, I forgot to update the issue.
With the latest version of klipper-toolchanger there should be no more problems.

I will close the issue now
